### PR TITLE
Fix: multirole sensor does not call MsgCB

### PR DESCRIPTION
**Pull request by ZhenshengLee**
Multirole sensor client behavior should process subscribed msg, and call `onMessageCallback`.

Thanks.

### CODE REVIEW

**Comment by ZhenshengLee** [comment]
@pabloinigoblasco

**Comment by pabloinigoblasco** [comment]
I need to review this in detail.
There is a underlaying problem behind that inocent disabled line.

Some of the examples broke with that change.

We will accept this PR but we need to recheck in detail some of the examples in runtime to check exactly what it is happening.

But we are on that, it will be accepted soon.

**Comment by ZhenshengLee** [comment]
> Some of the examples broke with that change.

You are right, and regression test are needed.

Thanks.

**Comment by ZhenshengLee** [comment]
Close this.

**Pull request closed without merging**
